
version: 2

models:
  - name: fact_series_rating
    description: Ratings and number of votes for all TV Series
    columns:
      - name: tconst
        description: Unique identifier of a title
        tests:
          - unique
          - not_null
  - name: fact_episode_rating
    description: Ratings and number of votes for all TV Episodes
    columns:
      - name: tconst
        description: Unique identifier of a title
        tests:
          - unique
          - not_null
      - name: parenttconst
        description: Unique identifier of a title
        tests:
          - not_null
